import type { FC, PropsWithChildren } from 'hono/jsx'
import { html, raw } from 'hono/html'
import type { SendResult } from '@pinsquirrel/mailgun'

/* Neo Brutalism, hand-written: apps/admin has no build step, so the tokens
   below — just the subset this app uses — are copied from
   apps/hono/src/styles/app.css (:root = light, .dark = dark) instead of being
   generated by Tailwind. Keep them in sync. */
const styles = `
  :root {
    color-scheme: light dark;

    --background: oklch(1 0 0);
    --foreground: oklch(0 0 0);
    --card: oklch(1 0 0);
    --card-foreground: oklch(0 0 0);
    --primary: oklch(0.5 0.18 229.78);
    --primary-foreground: oklch(1 0 0);
    --muted-foreground: oklch(0.3 0 0);

    /* Flash palette — Tailwind green/red 50-200-700 (light), 950-800-200 (dark) */
    --success-bg: #f0fdf4;
    --success-fg: #15803d;
    --success-border: #bbf7d0;
    --danger-bg: #fef2f2;
    --danger-fg: #b91c1c;
    --danger-border: #fecaca;
    --status-ok: #15803d;
    --status-bad: #b91c1c;
  }

  @media (prefers-color-scheme: dark) {
    :root {
      --background: oklch(0 0 0);
      --foreground: oklch(1 0 0);
      --card: oklch(0.1 0 0);
      --card-foreground: oklch(1 0 0);
      --primary: oklch(0.75 0.25 200);
      --primary-foreground: oklch(0 0 0);
      --muted-foreground: oklch(0.7 0 0);

      --success-bg: #052e16;
      --success-fg: #bbf7d0;
      --success-border: #166534;
      --danger-bg: #450a0a;
      --danger-fg: #fecaca;
      --danger-border: #991b1b;
      --status-ok: #86efac;
      --status-bad: #fca5a5;
    }
  }

  * { box-sizing: border-box; }

  body {
    font-family: 'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
      'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
    margin: 0;
    background: var(--background);
    color: var(--foreground);
  }

  .wrap { max-width: 880px; margin: 0 auto; padding: 2.5rem 1.25rem 4rem; }

  h1 { font-size: 1.875rem; font-weight: 700; line-height: 1.15; margin: 0 0 0.5rem; }
  .card h1 { font-size: 1.25rem; }
  .brand { font-weight: 900; text-transform: uppercase; letter-spacing: -0.025em; }
  .muted { color: var(--muted-foreground); font-size: 0.875rem; margin: 0; }

  .card {
    background: var(--card);
    color: var(--card-foreground);
    border: 2px solid var(--foreground);
    box-shadow: 4px 4px 0 0 var(--foreground);
    padding: 1.5rem;
    margin-top: 1.75rem;
  }

  form { margin: 0; }

  label {
    display: block;
    font-size: 0.875rem;
    font-weight: 500;
    margin: 1rem 0 0.5rem;
  }

  input, select, textarea {
    width: 100%;
    padding: 0.5rem 0.75rem;
    border: 2px solid var(--foreground);
    border-radius: 0;
    background: var(--background);
    color: var(--foreground);
    font: inherit;
    box-shadow: 2px 2px 0 0 var(--foreground);
  }

  input, select { height: 2.75rem; }

  input:focus, select:focus, textarea:focus {
    outline: none;
    box-shadow: 0 0 0 2px var(--card), 0 0 0 4px var(--primary), 2px 2px 0 0 var(--foreground);
  }

  textarea { min-height: 200px; resize: vertical; }

  button, .btn {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    white-space: nowrap;
    margin-top: 1.5rem;
    height: 2.75rem;
    padding: 0 1.5rem;
    border: 2px solid var(--foreground);
    border-radius: 0;
    background: var(--primary);
    color: var(--primary-foreground);
    font: inherit;
    font-size: 0.875rem;
    font-weight: 700;
    text-transform: uppercase;
    cursor: pointer;
    text-decoration: none;
    box-shadow: 4px 4px 0 0 var(--foreground);
    transition: all 150ms ease;
  }

  button:hover, .btn:hover {
    transform: translate(-2px, -2px);
    box-shadow: 6px 6px 0 0 var(--foreground);
  }

  button:active, .btn:active {
    transform: translate(2px, 2px);
    box-shadow: 2px 2px 0 0 var(--foreground);
  }

  button:focus-visible, .btn:focus-visible {
    outline: 2px solid var(--primary);
    outline-offset: 2px;
  }

  button:disabled { opacity: 0.5; pointer-events: none; }

  .btn-secondary { background: var(--background); color: var(--foreground); }
  .btn-sm { margin-top: 0; height: 2.25rem; padding: 0 0.75rem; font-size: 0.875rem; }

  .notice, .error {
    padding: 0.75rem;
    font-size: 0.875rem;
    font-weight: 500;
    border: 2px solid;
    box-shadow: 4px 4px 0 0 var(--foreground);
    margin: 0 0 1.25rem;
  }
  .notice { background: var(--success-bg); color: var(--success-fg); border-color: var(--success-border); }
  .error { background: var(--danger-bg); color: var(--danger-fg); border-color: var(--danger-border); }

  .inline-form { display: flex; gap: 0.75rem; align-items: stretch; }
  .inline-form input { flex: 1; }
  .inline-form button { margin-top: 0; }

  .row { display: flex; gap: 1rem; align-items: center; justify-content: space-between; flex-wrap: wrap; }
  .row button, .row .btn { margin-top: 0; }

  table { width: 100%; border-collapse: collapse; margin: 0.25rem 0 0; font-size: 0.875rem; }
  th, td {
    text-align: left;
    padding: 0.625rem 0.75rem;
    border-bottom: 2px solid color-mix(in oklab, var(--foreground) 20%, transparent);
  }
  th {
    color: var(--muted-foreground);
    font-weight: 600;
    font-size: 0.75rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    border-bottom: 2px solid var(--foreground);
  }
  tbody tr:last-child td { border-bottom: 0; }

  .ok { color: var(--status-ok); font-weight: 700; }
  .bad { color: var(--status-bad); font-weight: 700; }
`

const Layout: FC<PropsWithChildren<{ title: string }>> = ({
  title,
  children,
}) =>
  html`<!doctype html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${title} · PinSquirrel Admin</title>
        <style>
          ${raw(styles)}
        </style>
      </head>
      <body>
        <div class="wrap">${children}</div>
      </body>
    </html>`

export const LoginPage: FC<{
  environments: { name: string; label: string }[]
  error?: string
  selected?: string
  username?: string
}> = ({ environments, error, selected, username }) => (
  <Layout title="Sign in">
    <h1 class="brand">PinSquirrel Admin</h1>
    <p class="muted">
      Sign in with an admin account for the chosen environment.
    </p>
    <div class="card">
      {error ? (
        <div class="error" role="alert">
          {error}
        </div>
      ) : (
        ''
      )}
      <form method="post" action="/login">
        <label for="environment">Environment</label>
        <select id="environment" name="environment">
          {environments.map(e => (
            <option value={e.name} selected={e.name === selected}>
              {e.label}
            </option>
          ))}
        </select>
        <label for="username">Username</label>
        <input id="username" name="username" value={username ?? ''} required />
        <label for="password">Password</label>
        <input id="password" name="password" type="password" required />
        <button type="submit">Sign in</button>
      </form>
    </div>
  </Layout>
)

export const UnlockPage: FC<{ envLabel: string; error?: string }> = ({
  envLabel,
  error,
}) => (
  <Layout title="Unlock key">
    <h1>Unlock decryption key</h1>
    <p class="muted">{envLabel} — this key file is encrypted.</p>
    <div class="card">
      {error ? (
        <div class="error" role="alert">
          {error}
        </div>
      ) : (
        ''
      )}
      <form method="post" action="/unlock">
        <label for="passphrase">Passphrase</label>
        <input id="passphrase" name="passphrase" type="password" required />
        <button type="submit">Unlock</button>
      </form>
    </div>
  </Layout>
)

export const WaitlistPage: FC<{
  envLabel: string
  username: string
  rows: { id: string; username: string; email: string; joinedAt: string }[]
  notice?: string
  error?: string
}> = ({ envLabel, username, rows, notice, error }) => (
  <Layout title="Waitlist">
    <div class="row">
      <div>
        <h1>Waitlist · {rows.length}</h1>
        <p class="muted">
          {envLabel} — signed in as {username}
        </p>
      </div>
      <form method="post" action="/logout">
        <button class="btn-secondary" type="submit">
          Sign out
        </button>
      </form>
    </div>
    <div class="card">
      {notice ? (
        <div class="notice" role="status">
          {notice}
        </div>
      ) : (
        ''
      )}
      {error ? (
        <div class="error" role="alert">
          {error}
        </div>
      ) : (
        ''
      )}
      {rows.length === 0 ? (
        error ? (
          ''
        ) : (
          <p class="muted">No one is on the waitlist.</p>
        )
      ) : (
        <table>
          <thead>
            <tr>
              <th>Username</th>
              <th>Email</th>
              <th>Joined</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {rows.map(r => (
              <tr>
                <td>{r.username}</td>
                <td>{r.email}</td>
                <td class="muted">{r.joinedAt}</td>
                <td>
                  {/* Granting flips the user to Active, so the row drops off
                      the next render — the list is queried by Waitlist status. */}
                  <form method="post" action="/grant-access">
                    <input type="hidden" name="userId" value={r.id} />
                    <button class="btn-sm" type="submit">
                      Grant access
                    </button>
                  </form>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
      {rows.length > 0 ? (
        <a class="btn" href="/compose">
          Compose message
        </a>
      ) : (
        ''
      )}
    </div>
    <div class="card">
      <h1>Grant admin</h1>
      <p class="muted">
        Adds the Admin role to any existing account, on or off the waitlist.
        Roles are additive and granting twice changes nothing.
      </p>
      <form method="post" action="/grant-admin">
        <label for="admin-username">Username</label>
        <div class="inline-form">
          <input id="admin-username" name="username" required />
          <button type="submit">Grant admin</button>
        </div>
      </form>
    </div>
  </Layout>
)

export const ComposePage: FC<{
  envLabel: string
  recipientCount: number
  error?: string
  subject?: string
  body?: string
}> = ({ envLabel, recipientCount, error, subject, body }) => (
  <Layout title="Compose">
    <div class="row">
      <div>
        <h1>Compose message</h1>
        <p class="muted">
          {envLabel} — sends individually to {recipientCount} waitlisted{' '}
          {recipientCount === 1 ? 'person' : 'people'}.
        </p>
      </div>
      <a class="btn btn-secondary" href="/waitlist">
        Back
      </a>
    </div>
    <div class="card">
      {error ? (
        <div class="error" role="alert">
          {error}
        </div>
      ) : (
        ''
      )}
      <form method="post" action="/send">
        <label for="subject">Subject</label>
        <input id="subject" name="subject" value={subject ?? ''} required />
        <label for="body">Message (plain text)</label>
        <textarea id="body" name="body" required>
          {body ?? ''}
        </textarea>
        <button type="submit">Send to {recipientCount}</button>
      </form>
    </div>
  </Layout>
)

export const SentPage: FC<{ envLabel: string; results: SendResult[] }> = ({
  envLabel,
  results,
}) => {
  const sent = results.filter(r => r.ok).length
  const failed = results.length - sent
  return (
    <Layout title="Sent">
      <h1>Sent</h1>
      <p class="muted">
        {envLabel} — <span class="ok">{sent} delivered</span>
        {failed > 0 ? <span class="bad">{`, ${failed} failed`}</span> : ''}
      </p>
      <div class="card">
        <table>
          <thead>
            <tr>
              <th>Recipient</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {results.map(r => (
              <tr>
                <td>{r.recipient}</td>
                <td class={r.ok ? 'ok' : 'bad'}>
                  {r.ok ? 'sent' : (r.error ?? 'failed')}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <a class="btn btn-secondary" href="/waitlist">
          Back to waitlist
        </a>
      </div>
    </Layout>
  )
}
